# Generated by Django 3.1.5 on 2021-01-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=120, verbose_name='Lesson name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120, verbose_name='First name')),
                ('student_lastname', models.CharField(max_length=120, verbose_name='Last name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=120, verbose_name='Teacher name')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handler.lesson')),
            ],
        ),
    ]
